services:
  database:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: Hoothoot94/
      MYSQL_DATABASE: symfony_auth_app
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - database
    command: php -S 0.0.0.0:8000 -t public

  mailer:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql-data: